# Generated by Django 5.1 on 2024-09-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('post_user', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('good', models.PositiveIntegerField()),
                ('read', models.PositiveIntegerField()),
                ('readuser', models.TextField()),
            ],
        ),
    ]
