# Generated by Django 5.1 on 2024-09-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainpostapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='good',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='read',
            field=models.PositiveIntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='readuser',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
